### ISSUE TITLE
Please add embree version number when making a release

### ISSUE THREAD

**Issue by wilsonCernWq** [ospray/ospray#152]
Hi All

I think it will be better to specific the embree version used for producing the ospray release in the future. 

For example, 1.3.x only compiles with embree 1.6.x on my machine (not very sure about the number x, but 1.6.4 works for me), although it is written on the website that `Embree ray tracing kernels v2.13 or newer`. 

Thanks !

**Comment by jeffamstutz** [comment]
OSPRay should support v2.13.0. What errors are you seeing?

**Comment by wilsonCernWq** [comment]
They are linkage errors. For example when I try to compile an application with embree2.15.0
```
/home/sci/qwu/software/ospray-1.3.0.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetIntersectFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unU_3E_avx512knl'
/home/sci/qwu/software/ospray-1.3.0.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetOccludedFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unU_3E_sse4'
/home/sci/qwu/software/ospray-1.3.0.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetBoundsFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____UM_un_3C_unv_3E_unUREFs_5B_unRTCBounds_5D__3E_avx512knl'
/home/sci/qwu/software/ospray-1.3.0.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetOccludedFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unU_3E_avx'
/home/sci/qwu/software/ospray-1.3.0.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetOccludedFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unU_3E_avx2'
/home/sci/qwu/software/ospray-1.3.0.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetBoundsFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____UM_un_3C_unv_3E_unUREFs_5B_unRTCBounds_5D__3E_sse4'
/home/sci/qwu/software/ospray-1.3.0.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetIntersectFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unU_3E_avx512skx'
/home/sci/qwu/software/ospray-1.3.0.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetIntersectFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unU_3E_avx2'
/home/sci/qwu/software/ospray-1.3.0.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetOccludedFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unU_3E_avx512skx'
/home/sci/qwu/software/ospray-1.3.0.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetBoundsFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____UM_un_3C_unv_3E_unUREFs_5B_unRTCBounds_5D__3E_avx2'
/home/sci/qwu/software/ospray-1.3.0.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetIntersectFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unU_3E_avx'
/home/sci/qwu/software/ospray-1.3.0.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetIntersectFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unU_3E_sse4'
/home/sci/qwu/software/ospray-1.3.0.x86_64.linux/lib/libospray.so: undefined reference to `E_a::rtcSetBoundsFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____UM_un_3C_unv_3E_unUREFs_5B_unRTCBounds_5D(void, long long)'
/home/sci/qwu/software/ospray-1.3.0.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetOccludedFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unU_3E_avx512knl'
/home/sci/qwu/software/ospray-1.3.0.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetBoundsFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____UM_un_3C_unv_3E_unUREFs_5B_unRTCBounds_5D__3E_avx512skx'
collect2: error: ld returned 1 exit status
make[2]: *** [VolumeDisplay] Error 1
make[1]: *** [CMakeFiles/VolumeDisplay.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by jeffamstutz** [comment]
Did you build Embree v2.15.0 from source? This looks like more of an issue with your build of Embree as all of those have been in the library prior to v2.13.0.

It is possible that there could be a bug in our CMake detecting Embree's supported ISAs in the library which was found. Let me see if I can reproduce.

**Comment by johguenther** [comment]
I think this is a know inconvenience: Your application needs to be compiled with the same Embree version which OSPRay is compiled against (or vice versa). Thus, please recompile OSPRay with Embree v2.15 (from scratch to be sure to avoid any shortcuts), then it should actually work.
Background is that between v2.15 and v2.16 the ISPC API interface of Embree changed slightly, but enough to not have binary compatibility anymore.

**Comment by wilsonCernWq** [comment]
@jeffamstutz I downloaded the embree from its website.
@johguenther Yes, I agree and my self-compiled version works. But it is not convenient to compile ospray sometimes, that why I think it would be better to also note the embree version used in release. Otherwise we might need to test all the embree versions one by one.

**Comment by jeffamstutz** [comment]
Last question, are you building OSPRay from source? One fix we could make is to have our CMake find_package() config detect if ```libembree.so``` exists in the install first before looking for a separate Embree. Right now we deploy Embree with OSPRay in the tar/zip releases, but when using CMake to find OSPRay it will still look for an external Embree install (where version mismatches can occur).

Regardless, It looks like @johguenther's answer is the right one. You can safely assume that we deploy the latest Embree with our OSPRay binaries. You shouldn't encounter this problem when building OSPRay from source.

**Comment by wilsonCernWq** [comment]
`are you building OSPRay from source?` I did both, building OSPRay from source gives no error in my application, but the downloaded version gives me compilation error in my application.

`You can safely assume that we deploy the latest Embree with our OSPRay binaries.` This answer my question already. Thanks Jeff !

**Comment by jeffamstutz** [comment]
Cool, let us know if you run into any other issues. I'll make sure that we get the (somewhat) related fix in our find_package() config I as previously described.
